from dataclasses import dataclass


@dataclass
class OutputAttributesConfig:
    """Configuration for renaming output attributes added by roofer."""
    # Default names are shown below, matching the TOML example
    success: str = "rf_success"
    reconstruction_time: str = "rf_reconstruction_time"
    val3dity_lod12: str = "rf_val3dity_lod12"
    val3dity_lod13: str = "rf_val3dity_lod13"
    val3dity_lod22: str = "rf_val3dity_lod22"
    is_glass_roof: str = "rf_is_glass_roof"
    nodata_frac: str = "rf_nodata_frac"
    nodata_r: str = "rf_nodata_r"
    pt_density: str = "rf_pt_density"
    is_mutated: str = "rf_is_mutated"
    pc_select: str = "rf_pc_select"
    pc_source: str = "rf_pc_source"
    pc_year: str = "rf_pc_year"
    force_lod11: str = "rf_force_lod11"
    roof_type: str = "rf_roof_type"
    h_roof_50p: str = "rf_roof_elevation_50p"
    h_roof_70p: str = "rf_roof_elevation_70p"
    h_roof_min: str = "rf_roof_elevation_min"
    h_roof_max: str = "rf_roof_elevation_max"
    roof_n_planes: str = "rf_roof_n_planes"
    rmse_lod12: str = "rf_rmse_lod12"
    rmse_lod13: str = "rf_rmse_lod13"
    rmse_lod22: str = "rf_rmse_lod22"
    volume_lod12 = "rf_volume_lod12"
    volume_lod13 = "rf_volume_lod13"
    volume_lod22 = "rf_volume_lod22"
    h_ground: str = "rf_h_ground"
    slope: str = "rf_slope"
    azimuth: str = "rf_azimuth"
    extrusion_mode = "rf_extrusie"
    pointcloud_unusable = "rf_pw_unusable"
    h_roof_ridge = "rf_roof_ridge"
    roof_n_ridgelines = "rf_n_ridgelines"
